/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        "Neutrals/neutrals-1": "#ffffff",
        "Neutrals/neutrals-2": "#fcfcfd",
        "Neutrals/neutrals-3": "#f5f5f6",
        "Neutrals/neutrals-4": "#f0f0f1",
        "Neutrals/neutrals-5": "#d9d9dc",
        "Neutrals/neutrals-6": "#c0bfc4",
        "Neutrals/neutrals-7": "#8e8c95",
        "Neutrals/neutrals-8": "#5b5966",
        "Neutrals/neutrals-9": "#474553",
        "Neutrals/neutrals-10": "#292637",
        "Neutrals/neutrals-11": "#211f30",
        "Neutrals/neutrals-12": "#171427",
        "Neutrals/neutrals-13": "#030014",
        "washed-purple/washed-purple-50": "#f8f7ff",
        "washed-purple/washed-purple-100": "#e8e7ff",
        "washed-purple/washed-purple-200": "#dddcff",
        "washed-purple/washed-purple-300": "#cdcbff",
        "washed-purple/washed-purple-400": "#c4c1ff",
        "washed-purple/washed-purple-500": "#b5b2ff",
        "washed-purple/washed-purple-600": "#a5a2e8",
        "washed-purple/washed-purple-700": "#817eb5",
        "washed-purple/washed-purple-800": "#64628c",
        "washed-purple/washed-purple-900": "#4c4b6b",
        "washed-blue/washed-blue-50": "#f0f3ff",
        "washed-blue/washed-blue-100": "#d0daff",
        "washed-blue/washed-blue-200": "#bac9ff",
        "washed-blue/washed-blue-300": "#9ab0ff",
        "washed-blue/washed-blue-400": "#86a1ff",
        "washed-blue/washed-blue-500": "#6889ff",
        "washed-blue/washed-blue-600": "#5f7de8",
        "washed-blue/washed-blue-700": "#4a61b5",
        "washed-blue/washed-blue-800": "#394b8c",
        "washed-blue/washed-blue-900": "#2c3a6b",
        "Primary-blue/primary-blue-50": "#e6f0ff",
        "Primary-blue/primary-blue-100": "#b1d0ff",
        "Primary-blue/primary-blue-200": "#8cbaff",
        "Primary-blue/primary-blue-300": "#579aff",
        "Primary-blue/primary-blue-400": "#3686ff",
        "Primary-blue/primary-blue-500": "#0468ff",
        "Primary-blue/primary-blue-600": "#045fe8",
        "Primary-blue/primary-blue-700": "#034ab5",
        "Primary-blue/primary-blue-800": "#02398c",
        "Primary-blue/primary-blue-900": "#022c6b",
        "Primary-Purple/primary-purple-50": "#f1e6ff",
        "Primary-Purple/primary-purple-100": "#d3b0ff",
        "Primary-Purple/primary-purple-200": "#bd8aff",
        "Primary-Purple/primary-purple-300": "#9f54ff",
        "Primary-Purple/primary-purple-400": "#8d33ff",
        "Primary-Purple/primary-purple-500": "#7000ff",
        "Primary-Purple/primary-purple-600": "#6600e8",
        "Primary-Purple/primary-purple-700": "#5000b5",
        "Primary-Purple/primary-purple-800": "#3e008c",
        "Primary-Purple/primary-purple-900": "#2f006b",
        "brand/brand-washedPurple": "#b5b2ff",
        "brand/brand-washedBlue": "#6889ff",
        "brand/brand-primaryBlue": "#0468ff",
        "brand/brand-primaryPurple": "#7000ff",
        "brand/brand-dark": "#030014",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
